name: nhp
channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - azure-batch=11.0.*
  - azure-cosmos=4.2.*
  - azure-storage-blob=12.9.*
  - azure-storage-file-datalake=12.5.*
  - dill=0.3.*
  - numpy=1.22.*
  - pandas=1.4.*
  - pyarrow=6.0.*
  - pygam=0.8.*
  - python-dotenv=0.20.*
  - tqdm=4.63.*
  # dev dependencies
  - black=22.3.*
  - ipykernel=6.13.*
  - ipython=8.2.*
  - ipywidgets=7.7.*
  - jupyter_client=7.2.*
  - jupyter_core=4.9.*
  - jupyterlab_pygments=0.2.*
  - jupyterlab_widgets=1.1.*
  - matplotlib=3.5.*
  - nbconvert=6.5.*
  - nbconvert-core=6.5.*
  - nbconvert-pandoc=6.5.*
  - nbformat=5.4.*
  - notebook=6.4.*
  - pyjanitor=0.22.*
  - pytest=7.1.*
  - pytest-mock=3.7.*
  - pylint=2.14.*
  - widgetsnbextension=3.6.*