name: nhp
channels:
  - conda-forge
dependencies:
  - black=22.3.*
  - ipykernel=6.13.*
  - ipython=8.2.*
  - ipywidgets=7.7.*
  - jupyter_client=7.2.*
  - jupyter_core=4.9.*
  - jupyterlab_pygments=0.2.*
  - jupyterlab_widgets=1.1.*
  - nbconvert=6.5.*
  - nbconvert-core=6.5.*
  - nbconvert-pandoc=6.5.*
  - nbformat=5.4.*
  - notebook=6.4.*
  - pyjanitor=0.22.*
  - widgetsnbextension=3.6.*