name: nhp
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - azure-cosmos=4.3.*
  - azure-keyvault-secrets=4.6.*
  - azure-identity=1.12.*
  - azure-storage-blob=12.15.*
  - azure-storage-file-datalake=12.10.*
  - fastparquet=2023.2.*
  - numpy=1.23.*
  - pandas=1.5.*
  - python-dotenv=1.0.*
  - scipy=1.10.*
  - tqdm=4.65.*
  # dev dependencies
  - black=23.1.*
  - coverage=7.2.*
  - ipykernel=6.21.*
  - ipython=8.11.*
  - ipywidgets=8.0.*
  - jupyter_client=8.0.*
  - jupyter_core=5.2.*
  - jupyterlab_pygments=0.2.*
  - jupyterlab_widgets=3.0.*
  - matplotlib=3.7.*
  - nbconvert=7.2.*
  - nbconvert-core=7.2.*
  - nbconvert-pandoc=7.2.*
  - nbformat=5.7.*
  - notebook=6.5.*
  - pygam=0.8.*
  - pyjanitor=0.23.*
  - pylint=2.16.*
  - pytest=7.2.*
  - pytest-cov=4.0.*
  - pytest-mock=3.10.*
  - snakeviz=2.1.*
  # - sphinx=6.0.*
  # - sphinx_rtd_theme=1.2.*
  - widgetsnbextension=4.0.*