site_name: NHP Model Documentation
site_description: Documentation for the NHP Model project
site_url: https://connect.strategyunitwm.nhs.uk/nhp/model_documentation/

repo_url: https://github.com/the-strategy-unit/nhp_model
repo_name: the-strategy-unit/nhp_model

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            merge_init_into_class: true
            filters:
              - "!_version"
              - "!__main__"

nav:
  - Home: index.md
  - API Reference: reference/
