on:
  workflow_call:
    inputs:
      app-version:
        required: true
        type: string  
      data-version:
        required: true
        type: string  
      latest:
        required: false
        default: false
        type: boolean
    secrets:
      AZURE_CREDENTIALS:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      NHP_STORAGE_ACCOUNT:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Login to Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Build and push image'   
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:${{ inputs.app-version }} \
            --build-arg app_version=${{ inputs.app-version }} \
            --build-arg data_version=${{ inputs.data-version }} \
            --build-arg storage_account=${{ secrets.NHP_STORAGE_ACCOUNT }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:${{ inputs.app-version }}
          
      - name: 'Push latest'
        if: ${{ inputs.latest }}
        run: |
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:${{ inputs.app-version }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:latest