on:
  workflow_call:
    inputs:
      app-version:
        required: true
        type: string  
      data-version:
        required: true
        type: string  
      latest:
        required: false
        default: false
        type: boolean
    secrets:
      AZURE_CREDENTIALS:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      NHP_STORAGE_ACCOUNT:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # replaced progamatically if deploying to production
      VERSION: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Login to Container Registry'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Update version (production)
        if: ${{ inputs.latest }}
        run: |
          VERSION=`echo ${{ github.ref_name }} | awk 'BEGIN { FS="."; } { print ""$1"."$2; }'`
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 'Build and push image'
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:${{ env.VERSION }} \
            --build-arg app_version=${{ inputs.app-version }} \
            --build-arg data_version=${{ inputs.data-version }} \
            --build-arg storage_account=${{ secrets.NHP_STORAGE_ACCOUNT }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:${{ env.VERSION }}
          
      - name: 'Push latest'
        if: ${{ inputs.latest }}
        run: |
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:${{ env.VERSION }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:latest