on:
  workflow_call:
    inputs:
      docker-tag:
        required: true
        default: dev
        type: string
      app-version:
        required: true
        default: dev
        type: string
      data-version:
        required: true
        default: dev
        type: string  
      latest:
        required: false
        default: false
        type: boolean
    secrets:
      AZURE_CREDENTIALS:
        required: true
      REGISTRY_LOGIN_SERVER:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      NHP_STORAGE_ACCOUNT:
        required: true

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build image"
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/the-strategy-unit/nhp_model:pr-${{ github.event.number }}
          push: true
          cache-from: type=registry,ref=ghcr.io/the-strategy-unit/nhp_model:build-cache
          cache-to: type=registry,ref=ghcr.io/the-strategy-unit/nhp_model:build-cache,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/nhp_model.tar
          build-args: |
            app_version=${{ inputs.app-version }}
            data_version=${{ inputs.data-version }}

      - name: Upload image tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nhp_model
          path: nhp_model.tar
          retention-days: 1

      - name: Comment with container image link
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ A new build is available.

            You can use the following to use pull the image into your local environment:

            ``` bash
            docker pull ghcr.io/the-strategy-unit/nhp_model:pr-${{ github.event.number }}
            ```

            [Download Artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          edit-mode: replace

  deploy-ghcr:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: ["build-container"]
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Download image tarball
        uses: actions/download-artifact@v4
        with:
          name: nhp_model
          path: ${{ runner.temp }}

      - name: Load Docker image from tarball
        run: docker load -i ${{ runner.temp }}/nhp_model.tar

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build image"
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/the-strategy-unit/nhp_model:${{ inputs.docker-tag }}
          push: true
          cache-from: type=registry,ref=ghcr.io/the-strategy-unit/nhp_model:build-cache
          cache-to: type=registry,ref=ghcr.io/the-strategy-unit/nhp_model:build-cache,mode=max
          build-args: |
            app_version=${{ inputs.app-version }}
            data_version=${{ inputs.data-version }}

      - name: "Push latest"
        if: ${{ inputs.latest }}
        run: |
          docker tag ghcr.io/the-strategy-unit/nhp_model:${{ inputs.docker-tag }} ghcr.io/the-strategy-unit/nhp_model:latest
          docker push ghcr.io/the-strategy-unit/nhp_model:latest

  deploy-acr:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: ["build-container"]
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Download image tarball
        uses: actions/download-artifact@v4
        with:
          name: nhp_model

      - name: Load Docker image from tarball
        run: docker load -i nhp_model.tar

      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: "Login to Azure Container Registry"
        uses: azure/docker-login@v3
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build image"
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:${{ inputs.docker-tag }}
          push: true
          cache-from: type=registry,ref=ghcr.io/the-strategy-unit/nhp_model:build-cache
          build-args: |
            app_version=${{ inputs.app-version }}
            data_version=${{ inputs.data-version }}
            storage_account=${{ secrets.NHP_STORAGE_ACCOUNT }}
          
      - name: "Push latest"
        if: ${{ inputs.latest }}
        run: |
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:${{ inputs.docker-tag }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nhp_model:latest