name: Deploy schema.json to GitHub Pages 

on:
  workflow_call:
    inputs:
      docker-tag:
        required: true
        default: dev
        type: string
      app-version:
        required: true
        default: dev
        type: string
      data-version:
        required: true
        default: dev
        type: string

jobs:
  
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v5

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build image"
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ inputs.docker-tag }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false
          sbom: false
          build-args: |
            app_version=${{ inputs.app-version }}
            data_version=${{ inputs.data-version }}
