on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy Dev

jobs:
  deploy-dev-model:
    uses: ./.github/workflows/build_container.yaml
    with:
      docker-tag: dev
      app-version: dev
      data-version: dev
      latest: false
    secrets: inherit

  deploy-dev-schema:
    uses: ./.github/workflows/build_schema.yaml
    if: github.event_name == 'push'
    with:
      schema-tag: dev
    secrets: inherit