on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy Dev

jobs:
  deploy-ghcr-dev:
    uses: ./.github/workflows/build_container.yaml
    with:
      docker-tag: ghcr.io/the-strategy-unit/nhp_model:dev
      app-version: dev
      data-version: dev
    secrets: inherit

  deploy-dev-schema:
    uses: ./.github/workflows/build_schema.yaml
    with:
      schema-tag: dev
    secrets: inherit