on:
  push:
    tags:
      - 'v*.*.*'

name: Deploy Production

jobs:
  deploy-production:
  
    uses: ./.github/workflows/build_container.yaml
    with:
      app-version: ${{github.ref_name}} 
      data-version: ${{vars.data_version}}
      latest: true
    secrets: inherit

  deploy-schema:

    uses: ./.github/workflows/deploy_schema.yaml
    with:
      app-version: ${{github.ref_name}} 
