on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy Dev

jobs:
  deploy-dev:
    uses: ./.github/workflows/build_container.yaml
    with:
      app-version: dev 
      data-version: dev
    secrets: inherit
