on:
  pull_request:
    types: [opened, synchronize, reopened]

name: Deploy PR

jobs:
  
  deploy-ghcr-pr:
    uses: ./.github/workflows/build_container.yaml
    with:
      docker-tag: ghcr.io/the-strategy-unit/nhp_model:pr-${{ github.event.number }}
      app-version: dev
      data-version: dev
    secrets: inherit

  add-comment-to-pr:
    runs-on: ubuntu-latest
    needs: ["deploy-ghcr-pr"]
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "## ✅ A new build is available"

      - name: Comment with container image link
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ✅ A new build is available.

            You can use the following to use pull the image into your local environment:

            ``` bash
            docker pull ghcr.io/the-strategy-unit/nhp_model:pr-${{ github.event.number }}
            ```
          edit-mode: replace
