name: Linting and Type checking

on: pull_request

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/ruff-action@v4.0.0

  ruff-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/ruff-action@v4.0.0
        with:
          args: format --check --diff

  ty-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: "latest"
          activate-environment: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Generate Report
        run: uvx ty check .
